### ISSUE TITLE
how to use the analytics parameter?

### ISSUE THREAD

**Issue by trtg** [bul-ikana/hugo-cards#1]
What should the analytics parameter be set to in order to enable google analytics? Is it expecting the tracking ID or a full gtag.js snippet?

**Comment by bul-ikana** [comment]
Just the tracking ID. I'm gonna improve documentation this weekend.

**Comment by trtg** [comment]
Thanks- similarly was wondering what's expected for the disqus parameter?

**Comment by bul-ikana** [comment]
In disqus you should add the disqus_thread ID

**Comment by bul-ikana** [comment]
Updated readme with better documentation on configuration
