### ISSUE TITLE
specific tile images for articles when shown in list

### ISSUE THREAD

**Issue by codecraf8** [bul-ikana/hugo-cards#11]
When the list page is shown or a tag page is shown, there is one hard-coded image for each of the tiles. Ideally, there should be images specific to each title present in the list. How do we achieve that?

**Comment by bul-ikana** [comment]
I'm sorry you had issues with this theme. Documentation is updated on how to use the featured images on this theme.

> To change the featured image of your post, you must provide a `img` param in your post front-matter. This theme now supports [page resources](https://gohugo.io/content-management/page-resources/) so your featured image should be in the same directory than your `index.md` post file.
> 
> If you don't include one, a default image will be used. You can also customize this default image by changing the `defaultImage` param in your theme config. Be aware that this default image should be located on your `static/images` directory
