### ISSUE TITLE
We should not assume all images come from /images

### ISSUE THREAD

**Issue by saper** [bul-ikana/hugo-cards#14]
It seems that it is not possible to use Hugo's [image processing](https://gohugo.io/content-management/image-processing/) or [page resources](https://gohugo.io/content-management/page-resources/) features because this theme  seems to [hardcode .../images/... path](
https://discourse.gohugo.io/t/use-page-resources-img-instead-of-from-static-in-hugo-cards-theme/22785/2?u=saper) in few places:

* https://github.com/bul-ikana/hugo-cards/blob/94878efe46e39f248ab866a6e36ae6ef9d862306/layouts/_default/list.html#L14-L18

* https://github.com/bul-ikana/hugo-cards/blob/94878efe46e39f248ab866a6e36ae6ef9d862306/layouts/partials/sidebar.html#L3-L7

**Comment by bul-ikana** [comment]
I wasn't aware of page resources. They look really useful and make a lot of sense in the context of this theme which main feature is having a featured image. I made some changes to support them in #18 , but I am not sure if they cover all the scenarios you were thinking of. Feel free to submit another issue if there is something I didn't consider.
