### ISSUE TITLE
Theme works only with Hugo extended (with sass-css compiler)

### ISSUE THREAD

**Issue by Timur-P** [bul-ikana/hugo-cards#2]
According to new hugo policy, mentioned here, https://discourse.gohugo.io/t/hugo-extended-needed-for-hugo-fresh-theme/13844/23 it should work with regular Hugo version as well.

**Comment by bul-ikana** [comment]
Wasn't aware of this restriction. Will update as soon as possible. Thank you.

**Comment by bul-ikana** [comment]
Added the theme `resources` directory to the root of the theme, so it should work now with both versions of Hugo.
