### ISSUE TITLE
Lack of Search Function

### ISSUE THREAD

**Issue by nwigfieldzh** [bul-ikana/hugo-cards#22]
The default theme does not appear to include a search function. Is there a way to add search?

**Comment by bul-ikana** [comment]
Hi. As Hugo is a static site generator, there is no default way to add search functionality. However, Hugo docs have some recommendations on how to achieve this.

[https://gohugo.io/tools/search/](https://gohugo.io/tools/search/)

I am not planning on adding any of those soon. PRs are welcome! so if you end up adding one of those to your project please consider submitting it as a PR for the theme.
