### ISSUE TITLE
Change number of posts on the main page

### ISSUE THREAD

**Issue by zeibura** [bul-ikana/hugo-cards#27]
Is there any way to change the number of posts that display per page on the homepage so that it shows 12 per page instead of 10? I have been editing the /layouts/_default/list.html file in my implementation of the theme a bit but can't find anything on there that suggests I can change this.

Thanks a lot

**Comment by Marzal** [comment]
Have you tried to use the `paginate = 12` in the `config.toml` ?


https://gitlab.com/Marzal/hugo-cards-podcast/-/blob/main/config.toml#L7

**Comment by zeibura** [comment]
Fantastic, thanks a lot!
