### ISSUE TITLE
can't run example site

### ISSUE THREAD

**Issue by Moshiour027** [bul-ikana/hugo-cards#6]
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:4:5: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/head.html:7:2: executing "partials/head.html" at <partial "seo.html" .>: error calling partial: 
"/partials/seo.html:
execute of template failed: template: partials/seo.html
 executing "partials/seo.html" at <.Params.categories>: range can't iterate over one

**Comment by aQuaYi** [comment]
try to delete "category" or "categories" in every md file head in content folder.

**Comment by bul-ikana** [comment]
Yes. There was an update of the theme to make it compatible with hugo 0.57 and I forgot to update the example posts. I'll try to update that this weekend.

**Comment by Moshiour027** [comment]
I commented out the import of seo.html file and it works but that fix is needed. Is there any  Taxonomy Templates in this theme? if yes how to use them and if not can you please refer me to something. Thanks.

**Comment by bul-ikana** [comment]
This should be fixed in #9 .

For the record, if you want to use just one category, use:

`category: whatever`

if you need several categories, use:

`categories: [what, ever]`
