### ISSUE TITLE
Support for Tags

### ISSUE THREAD

**Issue by codecraf8** [bul-ikana/hugo-cards#8]
In the partials/list.html I added the following 

```
<div class="panel-footer">
            <small class="text-muted">
              {{ if gt .Params.tags 0 }}
              {{ range .Params.tags }}
              <a href="{{ "/tags/" | relURL }}{{ . | urlize }}" class="badge badge-primary"><span>{{ . }}</span></a>
              {{ end }}
              {{ end }}
            </small>
          </div>

```

All the tags are displayed but on clicking the tags all the posts are shown, no filtering is done. 

Added the tags, in the sidebar as well, similar story.

**Comment by codecraf8** [comment]
Any updates?

**Comment by bul-ikana** [comment]
The page for showing tags was missing. Added now. Feel free to reopen the issue if you still have problems.
